//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogla
    {
        public int OglasID { get; set; }
        public string start { get; set; }
        public string cilj { get; set; }
        public Nullable<System.TimeSpan> cas { get; set; }
        public Nullable<int> strosek { get; set; }
        public string opis { get; set; }
        public Nullable<int> st_oseb { get; set; }
    }
}
